more fixes

diff --git a/tree/usr/bin/eltrans b/tree/usr/bin/eltrans
--- a/tree/usr/bin/eltrans
+++ b/tree/usr/bin/eltrans
@@ -77,6 +77,7 @@ edit_preferences(){
 
     olduser="$( cat "$preferences" | grep username | sed 's/^.*:://g' )"
     oldpass="$( cat "$preferences" | grep password | sed 's/^.*:://g' )"
+
     $guitool --info --text=$"To collaborate with Elive making translations, you need to create yourself an account in http://www.elivecd.org/Help/Collaborate\n\nThanks a lot for your collaboration"
     resultado="$( $guitool --entry --title=$"Elive Translator Account" --text=$"Enter the Username of your Elive translator account" --entry-text="$olduser" || echo cancel )"
     verifyresult
@@ -169,8 +170,7 @@ try_translation_elive(){
     fi
 }
 ############################################################################
-commit_changes_elive()
-{
+commit_changes_elive(){
     if ! $guitool --question --text=$"Do you want to automatically send your translation to Elive that all the users can profit of your collaboration having its systems directly using your nice translation ?\n\nJust create yourself an account at http://www.elivecd.org/Help/Collaborate\n\nIf you don't send it you can have a conflict with your translation made and the possible new version in the server. So it is recommended to send the translations as fast as possible after to edit them (max. one hour aprox.), do not wait to continue after with them, just send it and you can run again eltrans later to continue with a non-finished translation\n\nNote: For that is needed to use a correct grammar and verify all the messages before to send them" ; then
 	return
     fi
@@ -203,7 +203,7 @@ commit_changes_elive()
     if [[ -s "/tmp/.${USER}-eltrans-logs" ]]; then
 	$guitool --info --text=$"I have found Warnings or Errors in your translation, please read them carefully and try to fix the problem manually. You've got a window open with the details of these errors. These messages include in the first field the exact number of the line of the problem. Enable line-number visualization in the editor if it is not enabled."
 
-	# FIXME: scite?? crap!
+	# FIXME: scite?
 	scite "$2"
     fi
     #}
@@ -222,7 +222,7 @@ commit_changes_elive()
 	$guitool --info --text="Translation sent sucessfully, Thanks a lot for your collaboration, it can be reviewed soon and included directly on Elive the next time."
 
     else
-	$term -e bash -c "svn commit --no-auth-cache --username \"$olduser\" --password \"$oldpass\" -m \"Eltrans auto:  |${1}|  in  |${4}|  by '$( awk -v var="$olduser" "BEGIN {print tolower(var)}" )'\" && sleep 1 && $guitool --info --text=\"Translation sent sucessfully, Thanks a lot for your collaboration, it can be reviewed soon and included directly on Elive the next time. You can check it directly at http://dev.elivecd.org/timeline, apart to use the features of the site like watch other translations, diff them, recover an old translation, etc...\" || $guitool --error --text=\"Error sending your translation, if you are using a Wrong Username or Password for the send please remove the file $preferences, otherwise the better solution is to remove your full translations project dir $elivetransdir and run the 'clean' or 'purge' option of eltrans. You can backup before your translated file and compare it with the 'meld' tool \""
+	$term -e bash -c "if svn commit --no-auth-cache --username \"$olduser\" --password \"$oldpass\" -m \"Eltrans auto:  |${1}|  in  |${4}|  by '$( awk -v var="$olduser" "BEGIN {print tolower(var)}" )'\" ; then sleep 1 ; $guitool --info --text=\"Translation sent sucessfully, Thanks a lot for your collaboration, it can be reviewed soon and included directly on Elive the next time. You can check it directly at http://dev.elivecd.org/timeline, apart to use the features of the site like watch other translations, diff them, recover an old translation, etc...\" ; else $guitool --error --text=\"Error sending your translation, if you are using a Wrong Username or Password for the send please remove the file $preferences, otherwise the better solution is to remove your full translations project dir $elivetransdir and run the 'clean' or 'purge' option of eltrans. You can backup before your translated file and compare it with the 'meld' tool \" ; fi"
 
     fi
 
@@ -313,13 +313,7 @@ translate_e17_new_language(){
 
     cd "${e17transdir}"
 
-    resultado="$( $guitool --entry --entry-text="${LANG%%_*}" --title=$"Select Language" --text=$"Select the language variant (locale) that you want to translate to, your system are using now the '${LANG%%_*}' value, but you can
-    use a more specific language like 'pt__BR' for the brazilian variant of portuguese language
-
-    We recommends <b>sincerely</b> to just use short value because if not, your translation don't cover the rest of variants,
-    use the long form only if you really want to made a specific version of your translation
-
-    Note: You can do translations to english too (clean english) using the 'en' value" || echo cancel )"
+    resultado="$( $guitool --entry --entry-text="${LANG%%_*}" --title=$"Select Language" --text=$"Select the language variant (locale) that you want to translate to, your system are using now the '${LANG%%_*}' value, but you can use a more specific language like 'pt__BR' for the brazilian variant of portuguese language.\n\nWe recommends <b>sincerely</b> to just use short value because if not, your translation don't cover the rest of variants, use the long form only if you really want to made a specific version of your translation\n\nNote: You can do translations to english too (clean english) using the 'en' value" || echo cancel )"
 
     verifyresult
     mylangdef="$resultado"
@@ -340,7 +334,7 @@ translate_e17_new_language(){
 		$poeditor "$mye17transdir/${mylangdef}.pot"
 
 		if ! grep -iq "Elive Translation tool" "$mye17transdir/${mylangdef}.pot" ; then
-		    sed -i "3a# \n# This translation was created/edited with the Elive translation tool" $mye17transdir/${mylangdef}.pot
+		    sed -i "3a# \n# This translation was created/edited with the Elive translation tool" "$mye17transdir/${mylangdef}.pot"
 		fi
 
 		edited=yes
@@ -583,6 +577,7 @@ translate_new(){
 ############################################################################
 main(){
     [[ -x /usr/bin/xterm ]] && term=xterm
+    [[ -x /usr/bin/terminology ]] && term=terminology
     [[ -x /usr/bin/urxvt ]] && term=urxvt
     [[ -z "$term" ]] && term=urxvt
 
