auto: untarzanice | PLEASE review this commit @Thanatermesis

diff --git a/tree/usr/bin/eltrans b/tree/usr/bin/eltrans
--- a/tree/usr/bin/eltrans
+++ b/tree/usr/bin/eltrans
@@ -174,7 +174,7 @@ dependencies_install(){
     # install dependencies if any needed
     if [[ -n "${dependencies[@]}" ]] ; then
         el_explain 0 "installing dependencies: __${dependencies[@]}__"
-        $guitool --info --text="$( eval_gettext "A few dependencies need to be installed first:" )"" $( echo "${dependencies[@]}" | tr ' ' ',' | sed -e 's|,|, |g' -e 's|, $||g' )"
+        $guitool --info --text="$( eval_gettext "A few packages need to be installed first:" )"" $( echo "${dependencies[@]}" | tr ' ' ',' | sed -e 's|,|, |g' -e 's|, $||g' )"
         el_dependencies_install "${dependencies[@]}"
     fi
 
@@ -246,11 +246,11 @@ preferences_edit(){
     pref_pass_cached_v="$( cat "$preferences_f" | LC_ALL=C grep "password" | sed 's/^.*:://g' )"
 
     #$guitool --info --text="$( eval_gettext "To collaborate with Elive making translations, you need to create yourself an account in https://www.elivecd.org/collaborate\n\nThanks a lot for your collaboration" )"
-    ui_user_answered="$( $guitool --entry --title="$( eval_gettext "Elive translator account" )" --text="$( eval_gettext "Enter the user name of your Elive translator account" )" --entry-text="$pref_user_cached_v" || echo cancel )"
+    ui_user_answered="$( $guitool --entry --title="$( eval_gettext "Translator account for Elive" )" --text="$( eval_gettext "Enter the user name of your Elive translator account" )" --entry-text="$pref_user_cached_v" || echo cancel )"
     ui_answer_check
     newuser="$ui_user_answered"
 
-    ui_user_answered="$( $guitool --password --title="$( eval_gettext "Elive translator account" )" --text="$( eval_gettext "Enter the password of your Elive translator account" )" || echo cancel )"
+    ui_user_answered="$( $guitool --password --title="$( eval_gettext "Translator account for Elive" )" --text="$( eval_gettext "Enter the password of your Elive translator account" )" || echo cancel )"
     ui_answer_check
     newpass="$ui_user_answered"
 
@@ -277,9 +277,9 @@ select_language(){
     if [[ "$language_user" = "en" ]] ; then
         if ! el_flag check proofreading_warning_show ; then
             #$guitool --info --text="$( eval_gettext "Thank you for collaborating in the proofreading of the messages. In your systray you can find a grammar checker tool. If you think that the spelling of the original messages is incorrect or not giving the right information to the user, feel free to improve them. If you do not understand what a message means, ask the developers." )"
-            $guitool --info --text="$( eval_gettext "IMPORTANT: The quality of the automatic pre-translations depends heavily on the grammatical and syntactical accuracy and correctness of the English text. For this, we use a special reverse-engineering trick explained in the forum. Using the Google Translator website in an inverse way, you need to examine the automated translation to a common language like Spanish or French, and modify it until the automated translation is correct. When everything looks good, use the new English message in Eltrans, if not, change a word or rewrite the sentence. This will save a lot of time for all the translators and will make the messages clearer and more understandable. More information about this technique can be found in the Forums." )"
+            $guitool --info --text="$( eval_gettext "IMPORTANT: The quality of the automatic pre-translations depends heavily on the grammatical and syntactical accuracy, and the clarity of the English text. For this, we use a special reverse-engineering trick explained in the forum. Basically using the Google Translator website in an inverse way, you need to examine the automated translation to a common language like Spanish or French, and modify it until the automated translation is correct. When everything looks good, use the new English message back to Eltrans. This will save a lot of time for all the translators and will make the automated translations clearer and more understandable. More information about this technique can be found in the Forums." )"
 
-            if ! $guitool --question --text="$( eval_gettext "Do you know already the procedure of the English proofreading method we use?" )" ; then
+            if ! $guitool --question --text="$( eval_gettext "Do you know already the procedure for the English approvals method that we use?" )" ; then
                 web-launcher "https://forum.elivelinux.org/t/eltrans-how-to-improve-the-english-sentences-in-elive-proofreading/1055" &
             fi
 
@@ -288,7 +288,7 @@ select_language(){
 
         # always have a window of google translator opened:
         if ! ps ux | grep -v grep | grep -qs "web-launcher.*translate.google.com" ; then
-            el_notify normal gtranslator "Google Translator" "$( eval_gettext "Do not close the google-translator window. You should follow the proofreading method that we use to proofread the Elive messages." )"
+            el_notify normal gtranslator "Google Translator" "$( eval_gettext "Do not close the google-translator window. You should follow the proofreading method that we use to verify the Elive messages." )"
             # always run a web browser with google translator since its the needed tool to use for it
             web-launcher --incognito --app="https://translate.google.com" &
         fi
@@ -361,12 +361,12 @@ translate_elive(){
         if [[ "${language_user}" = "en" ]] ; then
             if ! echo "$pref_user_cached_v" | grep -qsiE "^(Thanatermesis)$" ; then
 
-                $guitool --error --text="$( eval_gettext "Sorry! Translations require at least 90% of their original messages to be validated. We do this to ensure the good quality of the messages and to follow the strict use of our special technique. You can find more details in our Forums." )"
+                $guitool --error --text="$( eval_gettext "Sorry! Translations require at least 90% of their original messages to be approved. We do this to ensure the good quality of the messages and to follow the strict use of our special technique. You can find more details in our Forums." )"
                 # do not translate this one
                 return 0
             fi
         else
-            $guitool --warning --text="$( eval_gettext "Sorry! This translation has less than the 90% of its original messages validated, we need to wait for them to be validated first, otherwise our translating work will be lost later. In the meantime, you can select another application to translate." )"
+            $guitool --warning --text="$( eval_gettext "Sorry! This translation has less than the 90% of its original messages validated, we need to wait for them to be approved first, otherwise, our translating work will be lost later. In the meantime, you can select another application to translate." )"
 
             if $guitool --question --text="$( eval_gettext "If you have good English skills, and you also know another common language like French or Spanish natively. You can help improve the English sentences using our special reverse-engineering method. Do you want to know more about it?" )" ; then
                 web-launcher "https://forum.elivelinux.org/t/eltrans-how-to-proofread-the-original-messages-of-elive/1055" &
@@ -386,9 +386,9 @@ translate_elive(){
     if [[ -n "$recent_changes_diffed" ]] ; then
         # only me? ignore...
         if [[ "$recent_changes_authors" != "${pref_user_cached_v}" ]] ; then
-            $guitool --warning --text="$( eval_gettext "The file that you want to translate has been modified in the last 3 days by other collaborators. You should not worry about this message, this is only a notification to know that other translators worked recently on the same file to avoid possible conflicts between versions translated.\n\nThese translators was:" ) ${recent_changes_authors// /, }"
+            $guitool --warning --text="$( eval_gettext "The file that you want to translate has been modified in the last 3 days by other collaborators. You should not worry about this message, this is only a notification to know that other translators worked recently on the same file and avoid possible conflicts between versions translated.\n\nThese translators was:" ) ${recent_changes_authors// /, }"
 
-            if ! $guitool --question --text="$( eval_gettext "Do you want to continue editing this translation? Otherwise, you can select another application to translate" )" ; then
+            if ! $guitool --question --text="$( eval_gettext "Do you want to continue editing this translation? Otherwise, you can select another element to translate" )" ; then
                 return 0
             fi
         fi
@@ -398,7 +398,7 @@ translate_elive(){
     count_messages_completed "$_tr_app_d/${language_user}.po"
 
     if [[ "$count_msg_fuzzy_v" -ge "10" ]] ; then
-        el_notify normal gtranslator "$( eval_gettext "Suggestion" )" "$( eval_gettext "Tip: If there are messages needing an update ('Needs Improvement' type), but they are correctly translated, you can press Ctrl + Enter to mark it as valid." )"
+        el_notify normal gtranslator "$( eval_gettext "Suggestion" )" "$( eval_gettext "Tip: If there are messages that needs an improvement ('Needs work'), but that they are correctly translated, you can press Ctrl + Enter to mark it as valid." )"
     fi
 
     #
@@ -560,7 +560,7 @@ commit_changes_elive(){
     done
 
     local message_error_sending_translations
-    message_error_sending_translations="$( printf "$( eval_gettext "Error sending your translation. If you are using a Wrong Username or Password please remove the file '%s', you can also try the 'Clean' option. But if you have important work saved, first do a backup of your directory '%s' and use meld with it and your backup after you have made Eltrans working again" )" "$preferences_f" "$translating_elive_d" )"
+    message_error_sending_translations="$( printf "$( eval_gettext "Error sending your translation. If you are using a Wrong Username or Password please remove the file '%s'. You can also try the 'Clean' option. But if you have important work saved, first do a backup of your directory '%s', and after to have made Eltrans work again, use the tool meld between your backup and that directory to merge the changes." )" "$preferences_f" "$translating_elive_d" )"
 
     if ((is_blklist)) ; then
         $term -e bash -c "sleep 2"
@@ -716,7 +716,7 @@ EOF
 
 
             local translated_message
-            translated_message="$( printf "$( eval_gettext "IMPORTANT: There was an update of the file '%s' that conflicted with your version. It was removed so that Eltrans can work correctly. If you had on it an old translation that you do not want to lose, you can use with caution the tool '%s', to compare and merge the contents, it's important to respect the correct structure of these files and especially to keep the same newline characters on them. If you want to do that, close now Eltrans and run this command, after, start Eltrans again and send your translation. The command is:" )" "${conflicted_file_f}" "meld" )\n\nmeld /tmp/${USER}-translations-eltrans ${translating_d}"
+            translated_message="$( printf "$( eval_gettext "IMPORTANT: There was an update of the file '%s' that conflicted with your translated version. It was removed so that Eltrans can work correctly. If you had on it an old translation that you do not want to lose, you can use with caution the tool '%s', to compare and merge the contents, it's important to respect the correct structure of these files, and especially to keep the same newline characters on them. If you want to do that, close now Eltrans and run this command, after, start Eltrans again and send your translation. The command is:" )" "${conflicted_file_f}" "meld" )\n\nmeld /tmp/${USER}-translations-eltrans ${translating_d}"
 
             $guitool --warning --text="${translated_message}"
 
@@ -1168,7 +1168,7 @@ translate_new(){
 main(){
     el_debug
 
-    translated_message="$( printf "$( eval_gettext "Select the language (%s) that you want to translate to. Your system is actually set to '%s', for example '%s' for Portuguese or like '%s' (brazilian portuguese) if you need to translate to a derivative language specifically (only if the main language is not compatible).\n\nIt is strongly recommended to use the short language code, because otherwise your translation does not cover the other variants. Use the long form only if you really want to translate to a specific version of your language\n\nTo improve the original English messages use '%s'." )" "locale" "${LANG%%_*}" "pt" "pt_BR" "en" )"
+    translated_message="$( printf "$( eval_gettext "Select the language (%s) that you want to translate to. Your system is configured as '%s'. As an example '%s' is the code for Portuguese and '%s'  for the brazilian-portuguese variation, which is useful if you need to translate to that derivative language specifically.\n\nIt is strongly recommended to use the short code as language, because otherwise, your translation will only be shown to that variant. Use the long-form only if you really want to translate to a specific version of the language and the main one is already translated.\n\nTo improve the original English messages use '%s'." )" "locale" "${LANG%%_*}" "pt" "pt_BR" "en" )"
 
 
     [[ -x /usr/bin/xterm ]] && term=xterm
@@ -1225,7 +1225,7 @@ main(){
         web-launcher "https://www.elivecd.org/contact" &
         sleep 15
 
-        $guitool --info --text="$( eval_gettext "Enter your username and password after to have created your account." )"
+        $guitool --info --text="$( eval_gettext "Enter your username and password after having created your account." )"
         preferences_edit
     fi
 
