migration to the next version first complete attempt

diff --git a/tree/usr/bin/eltrans b/tree/usr/bin/eltrans
--- a/tree/usr/bin/eltrans
+++ b/tree/usr/bin/eltrans
@@ -18,6 +18,7 @@
 # TODO: make obsolete the old translations system
 # TODO: need to change to .po/.pot ? (t = template)/
 # TODO: add a system of "percentage of grammar completed" (in the description.txt maybe)
+# TODO: change (all?) the notify calls (popup) to be in the instructions one
 
 # remove reported issues in github
 
@@ -42,6 +43,9 @@ temp_script="${tempdir}/script.sh"
 : ${guitool=zenity}
 export guitool
 mode_only_e17_v="no" # Warning: This option inhabilite the Elive translators part, set it to "yes" if you want to use this tool ONLY for Enlightenment 17 translations
+
+# version of this tool, for compatibility
+export eltrans_version_v="2"
 
 rm -rf "${tempdir}"
 mkdir -p "${tempdir}"
@@ -119,7 +123,8 @@ dependencies_install(){
     # FIXME: wee need to add something in our conf file to say "yes, it is already installed", this check is not enough
     if ! dpkg -l | grep "myspell-${_lang}" | grep -q "^ii" ; then
 
-	ui_user_answered="$( apt-cache search myspell-${_lang} | grep "^myspell" | $guitool --list --text=$"Select the appropriate dictionary package from this list." --column=$"Package" || echo cancel )"
+	package_dict="$( apt-cache search myspell-${_lang} | grep "^myspell" )"
+	ui_user_answered="$( echo "$package_dict" | $guitool --list --height=210 --width=350 --text=$"Select the appropriate dictionary package from this list." --column=$"Package" || echo cancel )"
 
 	if [[ -n "$ui_user_answered" ]] && [[ "$ui_user_answered" != "cancel" ]] ; then
 	    packagename="$(echo "$ui_user_answered" | awk '{print $1}')"
@@ -131,12 +136,39 @@ dependencies_install(){
     # install dependencies if any needed
     if [[ -n "${dependencies[@]}" ]] ; then
 	el_explain 0 "installing dependencies: __${dependencies[@]}__"
-	$guitool --info --text=$"We need to install a few dependencies first:"" ${dependencies[@]}"
+	$guitool --info --text=$"We need to install a few dependencies first:"" $( echo "${dependencies[@]}" | tr ' ' ',' | sed -e 's|,|, |g' -e 's|, $||g' )"
 	el_dependencies_install "${dependencies[@]}"
     fi
 
 }
 
+############################################################################
+instructions_show(){
+    echo -e $"Original Messages:
+==================
+The original text can be not spelled correctly, or not even in an intuitive way, think about that the messages needs to be as short as possible and simple to understand, complex sentences are not good (and programmers explain things deeply, sometimes).
+
+It is not something really easy and it requires a good understanding of the grammar and even consider psychological aspects, but if you think that you can improve the original messages you are more than welcome! just do a translation to 'English' then.
+
+Grammar Checks:
+===============
+You have a nice automated system to check the grammar, for use it in a fast way you can follow the next procedure:
+- Press 'Ctrl + a, Ctrl + c' for copy the text in the box
+- Click in the 'LT' icon in the systray for do the grammar check
+
+Suggestion: use the 'detect language' option by default
+
+Corrections:
+============
+If you are doing corrections this means that these messages are mostly automatically generated, they can include the correct words but maybe not correctly spelled, not in human language or not understandable, simply improve them and you can click in the cloud icon when you have it done (Alt + U)
+
+Extras:
+=======
+
+For moving faster to the next message, press TAB, the down-key, and again TAB
+
+" | $guitool --text-info --editable --width=420 --height=500 1>/dev/null &
+}
 ############################################################################
 preferences_edit(){
     el_debug
@@ -155,7 +187,7 @@ preferences_edit(){
     ui_answer_check
     newuser="$ui_user_answered"
 
-    ui_user_answered="$( $guitool --entry --title=$"Elive Translator Account" --text=$"Enter the Password of your Elive translator account" --entry-text="$pref_pass_cached_v" || echo cancel )"
+    ui_user_answered="$( $guitool --password --title=$"Elive Translator Account" --text=$"Enter the Password of your Elive translator account" || echo cancel )"
     ui_answer_check
     newpass="$ui_user_answered"
 
@@ -170,7 +202,7 @@ preferences_edit(){
 translate_elive(){
     el_debug
 
-    local is_base_translation_avail _tr_app_d
+    local is_base_translation_avail _tr_app_d _tr_package_version_v
     _tr_app_d="$1"
     el_check_variables "_tr_app_d"
 
@@ -184,7 +216,7 @@ translate_elive(){
 
     $guitool --info --text=$"Important: You can also do translations in English. The English translations are the most important ones because it is the standard one where all the other translations come from, so it is imperitive they are correctly written (not in the <b>Tarzanic English</b> of the developer). In order to do English translations simply use the '<b>en</b>' value."
 
-    ui_user_answered="$( $guitool --entry --entry-text="${LANG%%_*}" --title=$"Select Language" --text=$"Select the language variant (locale) that you want to translate to, your system are using now the '${LANG%%_*}' value, but you can use a more specific language like 'pt__BR' for the brazilian variant of portuguese language.\n\nWe recommends <b>sincerely</b> to just use short value because if not, your translation don't cover the rest of variants, use the long form only if you really want to made a specific version of your translation, so, for you: '${LANG%%_*}'\n\nNote: You can do translations <b>to English</b> too (clean English) using the 'en' value" || echo cancel )"
+    ui_user_answered="$( $guitool --entry --entry-text="${LANG%%_*}" --title=$"Select Language" --text=$"Select the language variant (locale) that you want to translate to, your system is now set to the '${LANG%%_*}' value, but you can use a more specific language like 'pt__BR' for the brazilian variant of portuguese language.\n\nWe recommends <b>sincerely</b> to just use short value because if not, your translation don't cover the rest of variants, use the long form only if you really want to made a specific version of your translation\n\nFor improve the original English messages use the 'en' value" || echo cancel )"
 
     ui_answer_check
     language_user="$ui_user_answered"
@@ -195,7 +227,7 @@ translate_elive(){
     dependencies_install "$language_user"
 
     # run extra apps
-    if ! ps aux | grep -q "java.*languagetool.*tray" ; then
+    if ! ps aux | grep -v grep | grep -q "java.*languagetool.*tray" ; then
 	languagetool-tray &
     fi
 
@@ -225,15 +257,24 @@ translate_elive(){
 
     if [[ "$fuzzy_msgs_v" -ge "10" ]] ; then
 	notify-send -t 100000 $"Eltrans: If you've got messages that need an update (FUZZY) but they are correctly translated, you can press the cloud icon."" "$"(or the Alt + U key)"
-    else
-	notify-send -t 100000 $"Tip: For moving more faster to the next message, press TAB, the down-arrow, and TAB again"
+    #else
+	#notify-send -t 100000 $"Tip: For moving more faster to the next message, press TAB, the down-arrow, and TAB again"
     fi
 
     # for the translator tools
-    #sed -e '/"Project-Id-Version: /s|Version:.*$|Version: 1\\n"|g'
+    _tr_package_version_v="$( grep "Project-Id-Version: " "${_tr_app_d}/default.pot" | sed -e 's|^.*Version: ||g' -e 's|\\n.*$||g' | head -1 | grep "[[:digit:]]" )"
+    : ${_tr_app_d:="1.0"}
 
-    el_check_variables "app_poeditor"
+    sed -i "/\"Project-Id-Version: /s|^.*Version:.*$|Version: ${_tr_package_version_v}\\\n\"|g" "$_tr_app_d/${language_user}.pot"
+
+    instructions_show
+    sleep 1
+
     "$app_poeditor" "$_tr_app_d/${language_user}.pot"
+
+    # why fuck always all the applications are buggy ? im tired to fix things everywhere
+    sed -i "/\"Project-Id-Version: /s|^.*Version:.*$|Version: ${_tr_package_version_v}\\\n\"|g" "$_tr_app_d/${language_user}.pot"
+
 
     rm -f "$_tr_app_d/${language_user}.mo"
 
@@ -308,6 +349,13 @@ commit_changes_elive(){
 	| grep -vE "\.po.*: .*(translated message|fuzzy translation|untranslated message)*.*$" \
 	| grep "\.pot:" \
 	> "${logs_err}"
+
+    # only send translations in utf-8 mode
+    if ! grep -q "Content-Type:.*charset=UTF-8" ; then
+	echo $"Translated file doesn't looks like to be in UTF-8 mode" >> "${logs_err}"
+	echo $"It is strictly needed that the charset used is UTF-8" >> "${logs_err}"
+	echo $"Try to change the configuration in the editor for being UTF-8" >> "${logs_err}"
+    fi
 
     if [[ -s "${logs_err}" ]]; then
 	$guitool --info --text=$"I have found Warnings or Errors in your translation, please read them carefully and try to fix the problem manually. You've got a window open with the details of these errors. These messages include in the first field the exact number of the line of the problem. Enable line-number visualization in the editor if it is not enabled."
@@ -401,7 +449,7 @@ EOF
     rm -f "${temp_script}"
 
     if [[ -s "${logs_err}" ]]; then
-	$guitool --error --text=$"Error downloading the translations of Elive, check the reported message, try again later or remove your directory of translations in Projects/translations"
+	$guitool --error --text=$"Error downloading the translations of Elive, is your username and password correctly set? check the reported message, try again later or remove your directory of translations in Projects/translations"
 	cat "${logs_err}" | $guitool --text-info --width=650 --height=400
 	rm -f "${logs_err}"
 
@@ -487,7 +535,7 @@ translate_e17_new_language(){
 
     cd "${translating_e17_d}"
 
-    ui_user_answered="$( $guitool --entry --entry-text="${LANG%%_*}" --title=$"Select Language" --text=$"Select the language variant (locale) that you want to translate to, your system are using now the '${LANG%%_*}' value, but you can use a more specific language like 'pt__BR' for the brazilian variant of portuguese language.\n\nWe recommends <b>sincerely</b> to just use short value because if not, your translation don't cover the rest of variants, use the long form only if you really want to made a specific version of your translation\n\nNote: You can do translations to english too (clean english) using the 'en' value" || echo cancel )"
+    ui_user_answered="$( $guitool --entry --entry-text="${LANG%%_*}" --title=$"Select Language" --text=$"Select the language variant (locale) that you want to translate to, your system is now set to the '${LANG%%_*}' value, but you can use a more specific language like 'pt__BR' for the brazilian variant of portuguese language.\n\nWe recommends <b>sincerely</b> to just use short value because if not, your translation don't cover the rest of variants, use the long form only if you really want to made a specific version of your translation\n\nNote: You can do translations to English too (clean english) using the 'en' value" || echo cancel )"
 
     ui_answer_check
     language_user="$ui_user_answered"
@@ -687,7 +735,7 @@ count_messages_completed(){
 translate_new(){
     el_debug
 
-    local item_order_v item_lang_v tr_name_v tr_description_v pid
+    local item_order_v item_lang_v tr_name_v tr_version_v tr_package_name_v tr_enabled_v tr_description_v is_showed_message_upgrade pid
     el_check_variables "tempfile"
     el_check_dirs "$translating_d"
 
@@ -709,58 +757,78 @@ translate_new(){
 
 	for item_v in ${translating_d}/elive/*
 	do
-	    if [[ -d "$item_v" ]]; then
-		unset count_percent_v
+	    if [[ -s "${item_v}/settings" ]]; then
+		unset count_percent_v tr_name_v tr_version_v tr_description_v tr_package_name_v tr_enabled_v item_order_v
 
-		tr_name_v="$( basename $item_v )"
-		tr_description_v="$( cat "$item_v/description.txt" 2>/dev/null | head -1 )"
+		tr_name_v="$( basename "$item_v" )"
+		tr_version_v="$( grep "version_min:::" "${item_v}/settings" | tail -1 | awk -v FS=":::" '{print $2}')"
+		tr_description_v="$( grep "description:::" "${item_v}/settings" | tail -1 | awk -v FS=":::" '{print $2}')"
+		tr_package_name_v="$( grep "package_name:::" "${item_v}/settings" | tail -1 | awk -v FS=":::" '{print $2}')"
+		tr_enabled_v="$( grep "enabled:::" "${item_v}/settings" | tail -1 | awk -v FS=":::" '{print $2}')"
+
+		#tr_description_v="$( cat "$item_v/description.txt" 2>/dev/null | head -1 )"
+
+		# ignore disactivated translations
+		if [[ "${tr_enabled_v}" != "yes" ]] ; then
+		    el_explain 0 "note: translation for __${tr_name_v}__ is actually disactivated on purpose, not including it..."
+		    continue
+		fi
+
+		# checks
+		if [[ "${tr_version_v}" -gt "$eltrans_version_v" ]] ; then
+		    if ! ((is_showed_message_upgrade)) ; then
+			$guitool --error --text=$"Some translations requires a newer version of eltrans, please update it" &
+			is_showed_message_upgrade=1
+		    fi
+		    continue
+		fi
+
+
+		# preselect lang files to use
+		[[ -f "$item_v/${LANG%%_*}.pot" ]] && item_lang_v="${LANG%%_*}"
+		[[ -f "$item_v/${LANG%%.*}.pot" ]] && item_lang_v="${LANG%%.*}"
+
+
+		if [[ -z "$item_lang_v" ]]; then
+		    tr_description_v=$"NEW: ${tr_description_v} - 0 % completed"
+
+		else
+		    count_messages_completed "${item_v}/${item_lang_v}.pot" "$item_v"
+
+		    if [[ "${count_percent_v}" -ge "100" ]] ; then
+			msgmerge -U "$item_v/${item_lang_v}.pot" "$item_v/default.pot" 2>/dev/null 1>&2
+			#mv $item_v/${item_lang_v}.tmp.pot $item_v/${item_lang_v}.pot
+			count_messages_completed "$item_v/${item_lang_v}.pot" "$item_v"
+		    fi
+		    # Normal description set for different percentages
+		    if [[ "${count_percent_v}" = "100" ]] ; then
+			tr_description_v=$"- Completed - Translation is not needed in the '${item_lang_v}' language."
+			item_order_v=8
+		    else
+			tr_description_v="${tr_description_v} - ${count_percent_v} %"$" completed (${item_lang_v})"
+			item_order_v=2
+		    fi
+
+		    # If is fuzzy
+		    if [[ "$fuzzy_msgs_v" -ge "1" ]] && [[ "$count_percent_v" = "100" ]] ; then
+			tr_description_v=$"Needs ${fuzzy_msgs_v} corrections (${item_lang_v}) "
+			item_order_v=4
+		    fi
+		fi
+
 
 		if [[ -n "$tr_description_v" ]]; then
-
-		    [[ -f "$item_v/${LANG%%_*}.pot" ]] && item_lang_v="${LANG%%_*}"
-		    [[ -f "$item_v/${LANG%%.*}.pot" ]] && item_lang_v="${LANG%%.*}"
-
-
-		    if [[ -z "$item_lang_v" ]]; then
-			tr_description_v=$"NEW: ${tr_description_v} - 0 % completed"
-
-		    else
-			count_messages_completed "$item_v/${item_lang_v}.pot" "$item_v"
-
-			if [[ "${count_percent_v}" -ge "100" ]] ; then
-			    msgmerge -U "$item_v/${item_lang_v}.pot" "$item_v/default.pot" 2>/dev/null 1>&2
-			    #mv $item_v/${item_lang_v}.tmp.pot $item_v/${item_lang_v}.pot
-			    count_messages_completed "$item_v/${item_lang_v}.pot" "$item_v"
-			fi
-			# Normal description set for different percentages
-			if [[ "${count_percent_v}" = "100" ]] ; then
-			    tr_description_v=$"- Completed - Translation is not needed in the '${item_lang_v}' language."
-			    item_order_v=8
-			else
-			    tr_description_v="${tr_description_v} - ${count_percent_v} %"$" completed (${item_lang_v})"
-			    item_order_v=2
-			fi
-			# If is fuzzy
-			if [[ "$fuzzy_msgs_v" -ge "1" ]] && [[ "$count_percent_v" = "100" ]] ; then
-			    tr_description_v=$"Needs ${fuzzy_msgs_v} updates (${item_lang_v}) "
-			    item_order_v=4
-			fi
-		    fi
-
-
-		    if [[ -n "$tr_description_v" ]]; then
-			echo -e "${tr_name_v}\n${tr_description_v}" >> "${tempfile}_order_${item_order_v}"
-		    fi
+		    echo -e "${tr_name_v}\n${tr_description_v}" >> "${tempfile}_order_${item_order_v}_${count_percent_v}"
+		fi
 
 		fi
-	    fi
 	done
 
 	kill "$pid"
 
 
 	el_check_files "$tempfile"
-	ui_user_answered="$( cat "$tempfile" ${tempfile}_order_* | $guitool --list --width=600 --height=460 --title=$"Select an Element." --text=$"Select one element that you want to translate or to update in an existing translation\n\nNote: If the percent value is not 100 but it is fully translated,\nthis may be due to errors like incorrectly written codes (like '\\\ n')\n" --column=$"Element" --column=$"Description" || echo cancel )"
+	ui_user_answered="$( cat "$tempfile" ${tempfile}_order_* | $guitool --list --width=600 --height=460 --title=$"Select an Element." --text=$"Select one element that you want to translate or to update in an existing translation" --column=$"Element" --column=$"Description" || echo cancel )"
 	ui_answer_check
 
 	rm -f "$tempfile" ${tempfile}_order_*
@@ -836,7 +904,6 @@ main(){
 
 }
 ############################################################################
-#echo -e $"This is just a test message to see if that message translated works, ignore it"
 
 
 main "$@"
